version: "2"

linters:
  default: none
  enable:
    - errcheck
    - misspell
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    generated: strict
    presets:
      - comments
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: "QF1008: " # https://staticcheck.dev/docs/checks#QF1008

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/graffer-inc/go-commons

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

run:
  timeout: 10m
