version: "3.9"
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-nature-remo-go
    container_name: my-nature-remo-go
    working_dir: /go/src
    volumes:
      - .:/go/src/
    environment:
      - RUN_CONTEXT=
      - NATURE_ACCESS_TOKEN
      - MACKEREL_API_KEY
      - MACKEREL_SERVICE_NAME=my-nature-remo
    command: go run main.go

