name: Go

on: push

jobs:
  fmt:
    runs-on: ubuntu-latest
    env:
      RUN_CONTEXT:
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-go@v7.0.0
        with:
          go-version: 1.26.5
      - uses: actions/cache@v6.1.0
        with:
          path: ~/go/pkg/mod # GOMODCACHE
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: go fmt
        run: make fmt

  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-go@v7.0.0
        with:
          go-version: 1.26.5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          version: v2.12.2
